export default {
  A: "viseme_aa",
  B: "viseme_PP",
  C: "viseme_kk",
  D: "viseme_DD",
  E: "viseme_E",
  F: "viseme_FF",
  G: "viseme_kk",
  H: "viseme_TH",
  I: "viseme_I",
  J: "viseme_CH",
  K: "viseme_kk",
  L: "viseme_DD",
  M: "viseme_PP",
  N: "viseme_nn",
  O: "viseme_O",
  P: "viseme_PP",
  Q: "viseme_kk",
  R: "viseme_RR",
  S: "viseme_SS",
  T: "viseme_DD",
  U: "viseme_U",
  V: "viseme_FF",
  W: "viseme_aa",
  X: "viseme_kk",
  Y: "viseme_I",
  Z: "viseme_SS",
} as { [key: string]: string };
